services:
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - db:/var/lib/postgresql/data

  api: 
    build: ./backend
    ports: 
      - "3001:3001"
    env_file: 
      - ./backend/.env
    depends_on:
      - db

  web:
    build: ./frontend
    ports: 
      - "3000:80" 
    depends_on:
      - api
    env_file: 
      - ./frontend/.env

volumes:
  db: