const Summary = () => {
  return (
    <div className="home__main-description">
      <h2 id="features-summary" style={{ fontWeight: "700" }}>
        AI Tasks Manager was designed to help you align tasks with predefined
        goals, thereby boosting your productivity and goal achievement!
      </h2>
      <h3>
        Start by envisioning your goals across various life domains - from
        career milestones to personal growth, health and wellness, finances,
        leisure, and more. Then, break down these aspirations into manageable
        monthly goals, setting the state for a productive journey ahead!
      </h3>
      <h3>
        Plan your week, aligning tasks with your overarching objectives.
        Identifying their individual priority levels will help you to ensure
        that critical tasks receive the attention they deserve.
      </h3>
      <h3>
        {" "}
        As you progress, update your task status to track your journey
        effectively. By splitting larger tasks into smaller actionable steps,
        you'll enhance productivity and maintain motivation.
      </h3>
      <h3>
        Throughout your journey, monitor your progress and check the analysis
        generated by an AI model{" "}
        <span style={{ fontWeight: "700" }}>(OpenAI model GPT-4)</span> and
        receive personalized insights to stay aligned with your goals.
      </h3>
      <h3>
        Are you ready to elevate your productivity? Start your journey with AI
        Task Manager today!
      </h3>
    </div>
  );
};
export default Summary;
